name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest 
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
    
    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

    - name: Upload Dragon text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest 
    steps:
    - name: Sleep for 10 seconds
      run: sleep 10
    
    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

    - name: Download Dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
 
  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest 
    steps:
    - name: Download Dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
        
    - name: Read File
      run: cat dragon.txt
    
    - name: Deploy
      run: echo Deploying ... .. .

    - name: Sleep for 30 seconds
      run: sleep 30

    

 
 #   ascii_job:
 #       runs-on: ubuntu-latest
 #       steps:
 #       - name: Checkout Repo
 #         uses: actions/checkout@v4   

 #       - name: List Repo Files
 #         run: ls -ltra

 #       - name: Executing shell script
 #         run: |
 #           chmod +x ascii-script.sh
 #           ./ascii-script.sh



